# -*- coding: utf-8 -*-
"""Pythontask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RrUcwwy5I2DTRn5xwojSMqZAiAkjiNPB

# **Accept a file name and a number (x). Display x lines from the top of the file.  Check if the file exists and is readable. The value of x should not exceed the total number of lines in the files. Display suitable messages in case an error is encountered.**
"""

fp = open("data.txt", 'w')  #open file to write the content in the file.
for i in range(10):
     fp.write("This is line %d\r\n" % (i+1)) # Content of the file
fp.close()                  # close the file.

# Read line by line from the file
fp = open("data.txt")             # fp is file pointer.
lines = fp.readlines()            # Command Used for read lines one by one.
for line in lines:
  print(line)                      # To print all the lines.
fp.close()

#Check if the file exists 

import os.path

print("case 1")
if os.path.isfile('data.txt'):
    print ("File exist")
else:
    print ("File not exist")

print("case 2")
if os.path.isfile('ZXC.txt'):
    print ("File exist")
else:
    print ("File not exist")

#Check if the file is readable 

print("type 1")
fp = open("data.txt", "r")
print(fp.readable())

print("type 2")
fp = open("data.txt")
print(fp.readable())

fp.close()

# Print the number of lines in a file
fp = open("data.txt", "r")
line_count = len(lines)
fp. close()
print(line_count)

"""# **The value of x should not exceed the total number of lines in the files. Display suitable messages in case an error is encountered.**"""

#case 1

x = 8
if line_count > x:
  print("The value of x not exceed the number of lines in file")
elif line_count < x:
  print("The value of x exceed the number of lines in file")
else:
  print("Error occured Try again with new value of x")

#case 2

x = 15
if line_count > x:
  print("The value of x not exceed the number of lines in file")
elif line_count < x:
  print("The value of x exceed the number of lines in file")
else:
  print("Error occured Try again with new value of x")

#case 3

x = 10
if line_count > x:
  print("The value of x not exceed the number of lines in file")
elif line_count < x:
  print("The value of x exceed the number of lines in file")
else:
  print("Error occured Try again with new value of x")